version: "3.8"
services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: springcanteen
    ports:
      - "5432:5432"
    volumes:
      - db_file:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d springcanteen"]
      interval: 1s
      timeout: 5s
      retries: 20
    networks:
      - backend

  backend:
    build: ./backend/springcanteen
    restart: on-failure
    volumes:
      - ./backend/springcanteen:/app
      - backend_data:/app/data
    depends_on:
      database:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.datasource.url" : "jdbc:mysql://database:3306/VTdb?allowPublicKeyRetrieval=true&useSSL=false",
          "spring.datasource.username" : "root",
          "spring.datasource.password" : "root",
          "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
          "spring.jpa.hibernate.ddl-auto" : "update",
          "jwt.secret_key" : "413F4428472B4B6250655368566D5970337336763979244226452948404D6351",
          "jwt.expirationtime.access" : "1200000",
          "jwt.expirationtime.refresh" : "172800000"
        }'
    healthcheck:
      test: curl --fail --silent localhost:8080/actuator/health || exit 1
      interval: 2s
      timeout: 30s
      retries: 200
      start_period: 10s
    networks:
      - backend
      - frontend
    labels:
      - traefik.enable=true
      - traefik.http.routers.backend.rule=PathPrefix(`/api`)
      - traefik.http.services.backend.loadbalancer.server.port=8080
      - traefik.http.routers.backend.entrypoints=web

  kiosk:
    build: ./frontend/SpringKiosk/material-ui-vite-ts
    restart: on-failure
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - frontend
    labels:
      - traefik.enable=true
      - traefik.http.routers.kiosk.rule=PathPrefix(`/`)
      - traefik.http.services.kiosk.loadbalancer.server.port=5173
      - traefik.http.routers.kiosk.entrypoints=web
    environment:
      - VITE_HOST=localhost

  digital-signage:
    build: ./frontend/DigitalSignage
    restart: on-failure
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - frontend
    labels:
      - traefik.enable=true
      - traefik.http.routers.digital-signage.rule=PathPrefix(`/signage`)
      - traefik.http.services.digital-signage.loadbalancer.server.port=5173
      - traefik.http.routers.digital-signage.entrypoints=web
    environment:
      - VITE_HOST=localhost

  traefik:
    image: traefik:v2.11
    ports:
      - "80:80"
      - "8080:8080"
    depends_on:
      backend:
        condition: service_healthy
      kiosk:
        condition: service_started
      digital-signage:
        condition: service_started
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./proxy/traefik.yml:/etc/traefik/traefik.yml"
    restart: unless-stopped
    networks:
      - backend
      - frontend

volumes:
  db_file:
  backend_data:

networks:
  backend:
  frontend: