FROM node:18-alpine AS builder

WORKDIR /app

COPY package.json .
COPY . .

ENV VITE_HOST=deti-tqs-02.ua.pt

RUN npm install
RUN npm run build

FROM nginx:1.21-alpine

WORKDIR /app

COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 5173

CMD ["nginx", "-g", "daemon off;"]